version: '3.8'

services:
  front-end:
      container_name: front-end
      build:
        context: ./frontend-web/PXL-NIEUWSARTIKELEN-FRONTEND
        dockerfile: Dockerfile
      ports:
        - "9000:80"

  mysql-db-post:
    image: mysql:8.0
    container_name: mysql-db-post
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: postservice_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - mysql-data-1:/var/lib/mysql

  mysql-db-review:
    image: mysql:8.0
    container_name: mysql-db-review
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reviewservice_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:  
      - "3307:3306"
    volumes:
      - mysql-data-2:/var/lib/mysql

  mysql-db-comment:
    image: mysql:8.0
    container_name: mysql-db-comment
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: commentservice_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:  
      - "3308:3306"
    volumes:
      - mysql-data-3:/var/lib/mysql

  
  rabbitmq:
    image: rabbitmq:4.0-management 
    container_name: rabbitmq
    ports:
      - "5672:5672"     
      - "15672:15672"   
    environment:
      RABBITMQ_DEFAULT_USER: admin   
      RABBITMQ_DEFAULT_PASS: admin   

volumes:
  mysql-data-1:
  mysql-data-2:
  mysql-data-3:
